# Permalinks
permalink:      :title

# Setup
title:          The Ring Cycle
baseurl:        "/ring-cycle"
url:            "mattsugihara.github.io/ring-cycle"

# Assets
sass:
  sass_dir:     style
  style:        :compressed

# Build settings
markdown:       kramdown

# About
# author:
#   name:         Chester How
#   url:          http://chester.how
#   email:        chesterhow@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

collections:
  - characters