# Permalinks
permalink:      :title

# Setup
title:          The Ring Cycle
baseurl:        "/ring-cycle"
url:            "mattsugihara.github.io/ring-cycle"

# Assets
sass:
  sass_dir:     style
  style:        :compressed

# Build settings
markdown:       kramdown

# Collections
collections:
  - characters